version: '3.4'

services:
  prophet_model:
    container_name: prophet-model
    image: rkrikbaev/prophet-model:latest
    command: [ "gunicorn", "-b", "0.0.0.0:8007", "api:api", "--timeout", "1000", "--log-level", "debug" ]
    ports:
      - 8007:8007
    volumes:
      - /opt/mlservices/prophet_model/app:/app
    environment:
      - LOG_LEVEL=DEBUG
