version: '3.4'

services:
  prophet_model:
    image: prophet_model
    command: [ "gunicorn", "-b", "0.0.0.0:8007", "api:api", "--timeout", "1000", "--log-level", "debug" ]
    ports:
      - 8005:8005
    volumes:
      - /opt/mlservices/prophet_model/app:/app
    environment:
      - LOG_LEVEL=DEBUG
